### ISSUE TITLE
Unable to resolve module `styled-components/native` 

### ISSUE THREAD

**Issue by nihalgadhavi9** [junhoyeo/react-native-bubble-tabbar#3]
Unable to resolve module `styled-components/native` from `node_modules/react-native-bubble-tabbar/lib/BubbleTabBar.js`: styled-components/native could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

**Comment by junhoyeo** [comment]
Thanks for leaving this issue 🙂
I'm really sorry to check this late. Should have a alarm or something 😥

https://github.com/junhoyeo/react-native-bubble-tabbar/blob/1795b68556189d29fbe95c4acb7ff959186b9607/package.json#L17-L20

As you see in the package.json file above, I referenced the `styled-components` module as a peerdependency, so you must install that before you use this module. `yarn add styled-components` will do fine.
My mistake; I must have documented it.

**Comment by junhoyeo** [comment]
I've documented that. Can you mind to try again after installing `styled-components`?
