### ISSUE TITLE
[v0.0.10] cannot import module

### ISSUE THREAD

**Issue by abathz** [junhoyeo/react-native-bubble-tabbar#9]
i just update version of `react-native-bubble-tabbar` from `0.0.9` to `0.0.10`. I got error message like this:

`error: Error: While trying to resolve module react-native-bubble-tabbar from file /Users/adlifariz/Dev/komodo-mobile/packages/komodobuyer/src/routes/Home.navigator.tsx, the package /Users/adlifariz/Dev/komodo-mobile/node_modules/react-native-bubble-tabbar/package.json was successfully found. However, this package itself specifies a main module field that could not be resolved (/Users/adlifariz/Dev/komodo-mobile/node_modules/react-native-bubble-tabbar/lib/index.js.`

I hope this bug can be solve in next version thank you 🙏🏻

**Comment by junhoyeo** [comment]
Bumped the version today. I'm really sorry for the late reply again 😥

**Comment by junhoyeo** [comment]
It works well now 🙏🙏🙏
